name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [21] # Use Java 21
        os: [ubuntu-latest, windows-latest] # Run on latest OS versions
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

# Why though
#      - name: Make Gradle Wrapper executable
#        if: ${{ runner.os != 'Windows' }}
#        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Capture Build Artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/